name: Build Intel Extension for PyTorch

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build_windows:
    runs-on: windows-latest # Using the latest Windows Server environment

    defaults:
      run:
        shell: powershell # Using PowerShell for better scripting on Windows

    steps:

      - name: Install Intel oneAPI Base Toolkit
        id: install_oneapi
        run: |
          echo "Attempting to download and install Intel oneAPI Base Toolkit..."
          $ProgressPreference = 'SilentlyContinue'
          # IMPORTANT: Replace this URL with the actual, stable download link for the oneAPI Base Toolkit offline installer
          $InstallerUrl = "https://registrationcenter-download.intel.com/akdlm/IRC_NAS/e5785fb3-b5a7-4b97-89bc-918adab1f77d/intel-oneapi-base-toolkit-2025.1.3.8_offline.exe" 
          $InstallerPath = "C:\temp\oneapi_installer.exe"
          $InstallDir = "C:\Program Files (x86)\Intel\oneAPI" # Default, used for setvars.bat path

          # Check if already installed (e.g., from a cached runner)
          if (Test-Path "$InstallDir\setvars.bat") {
            echo "oneAPI seems to be already installed (found setvars.bat). Skipping download/installation."
            echo "setvars_path=$InstallDir\setvars.bat" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            exit 0
          }

          New-Item -ItemType Directory -Force -Path "C:\temp" | Out-Null
          echo "Downloading oneAPI Base Toolkit installer from $InstallerUrl..."
          try {
            # Ensure you have a valid URL above
            if ($InstallerUrl -eq "YOUR_ONEAPI_BASEKIT_OFFLINE_INSTALLER_URL_HERE") {
                echo "::error::Installer URL is still the placeholder. Please update it in the workflow file."
                exit 1
            }
            Invoke-WebRequest -Uri $InstallerUrl -OutFile $InstallerPath -UseBasicParsing
            echo "Installer downloaded. Starting silent installation..."

            echo "----------------------------Listing components from installer:"
            # Command to list components based on Intel's documentation
            $listComponentsArgs = "-s -a --list-components"
            echo "Running: $InstallerPath $listComponentsArgs"
            
            # Execute and capture output
            $processInfo = New-Object System.Diagnostics.ProcessStartInfo
            $processInfo.FileName = $InstallerPath
            $processInfo.Arguments = $listComponentsArgs
            $processInfo.RedirectStandardOutput = $true
            $processInfo.RedirectStandardError = $true
            $processInfo.UseShellExecute = $false
            $process = New-Object System.Diagnostics.Process
            $process.StartInfo = $processInfo
            $process.Start() | Out-Null # Start the process
            # Wait for the process to exit, and capture output.
            # May need a timeout if the process hangs, but --list-components should be quick.
            $process.WaitForExit() 
            
            $output = $process.StandardOutput.ReadToEnd()
            $errorOutput = $process.StandardError.ReadToEnd()
            
            echo "--- Component List Output (Exit Code: $($process.ExitCode)) ---"
            echo $output
            if (-not [string]::IsNullOrWhiteSpace($errorOutput)) {
              echo "--- Component List Error Output ---"
              echo $errorOutput
            }
            echo "-------------------------------------"

            # Command based on Intel's documentation:
            # -s for the extractor, -a to pass args to installer
            # --silent for installer, --eula accept is required
            # --components: intel.oneapi.win.dpcpp-compiler (guess), intel.oneapi.win.mkl (guess), intel.oneapi.win.tbb.devel (from docs)
            # -p=NEED_VS2022_INTEGRATION=0 to skip VS integration with VS 2022 (GitHub runner default)
            # NOTE: The exact component IDs for DPC++ and MKL might need verification if the build fails later.
            #       You can get a list via:  $InstallerPath -s -a --list-components
            $targetComponents = "intel.oneapi.win.cpp-dpcpp-common:intel.oneapi.win.mkl.devel:intel.oneapi.win.tbb.devel"
            $oneApiArgs = "-s -a --silent --eula accept --components=$targetComponents -p=NEED_VS2022_INTEGRATION=0"
            
            echo "Running installer with arguments: $oneApiArgs"
            Start-Process -FilePath $InstallerPath -ArgumentList $oneApiArgs -Wait -NoNewWindow
            
            if ($LASTEXITCODE -ne 0) {
              echo "::error::oneAPI installation failed with exit code $LASTEXITCODE."
              # You could try to output installer logs here if you know their location.
              # e.g., $logPath = "C:\ProgramData\Intel\Logs\oneAPI_bootstrapper.log" (path may vary)
              # if (Test-Path $logPath) { Get-Content $logPath | Select-Object -Last 50 }
              exit 1
            }
            echo "oneAPI installation finished successfully."
            
            # Verify setvars.bat exists after installation
            if (Test-Path "$InstallDir\setvars.bat") {
              echo "setvars_path=$InstallDir\setvars.bat" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            } else {
              echo "::error::setvars.bat not found at $InstallDir\setvars.bat after oneAPI installation."
              echo "Please check the installation directory and if the correct components providing setvars.bat were installed."
              exit 1
            }
          } catch {
            echo "::error::Failed to download or run oneAPI installer: $($_.Exception.Message)"
            exit 1
          }
        shell: powershell

      - name: Checkout IPEX Repository
        uses: actions/checkout@v4
        with:
          repository: 'toolyq/intel-extension-for-pytorch' # Specify the IPEX repo
          submodules: 'recursive' # Checkout submodules if any

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools ninja psutil packaging
          echo "Installing PyTorch 2.7.0 CPU version..."
          pip install torch==2.7.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Build Intel Extension for PyTorch
        id: build_ipex
        env:
          PYTHONIOENCODING: "UTF-8"
          PYTHONUTF8: "1"
        run: |
          $SetvarsPath = "${{ steps.install_oneapi.outputs.setvars_path }}"
          if (-not $SetvarsPath -or !(Test-Path $SetvarsPath)) {
            echo "::error::setvars.bat path ('$SetvarsPath') not found or not valid from previous step."
            $DefaultSetvarsPath = "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
            echo "Trying default Intel oneAPI setvars.bat path: $DefaultSetvarsPath"
            if (Test-Path $DefaultSetvarsPath) {
              $SetvarsPath = $DefaultSetvarsPath
            } else {
              echo "::error::Default setvars.bat ('$DefaultSetvarsPath') also not found. Cannot proceed with build."
              exit 1
            }
          }

          echo "Using setvars.bat from: $SetvarsPath"

          $ScriptContent = @"
          @echo off
          echo Calling "%SETVARS_PATH%" intel64 vs2022...
          call "%SETVARS_PATH%" intel64 vs2022
          if %errorlevel% neq 0 (
            echo ::error::Failed to initialize oneAPI environment using setvars.bat. Exit code: %errorlevel%
            exit /b %errorlevel%
          )
          echo Environment initialized. Starting Python build for IPEX...
          python setup.py bdist_wheel -DUSE_NINJA=ON -DCMAKE_GENERATOR_PLATFORM=x64
          if %errorlevel% neq 0 (
            echo ::error::Python build (setup.py bdist_wheel) failed. Exit code: %errorlevel%
            exit /b %errorlevel%
          }
          echo Build command finished successfully.
          "@

          $TempBatchDir = "C:\temp"
          $TempBatchFile = Join-Path $TempBatchDir "build_script.bat"
          New-Item -ItemType Directory -Force -Path $TempBatchDir | Out-Null
          Set-Content -Path $TempBatchFile -Value $ScriptContent -Encoding Ascii

          echo "Executing temporary build script: $TempBatchFile"
          cmd.exe /c "$TempBatchFile"

          if ($LASTEXITCODE -ne 0) {
            echo "::error::Build script execution failed with exit code $LASTEXITCODE"
            exit 1
          }
          echo "Build process completed via batch script."

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipex-wheel-windows-py310-torch27
          path: dist/*.whl
          if-no-files-found: error
